spring.application.name=No10_H2DBProject


spring.jpa.show-sql=true

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=thirumala
spring.datasource.password=thirumala@123